version: '3.8'

services:
  # MySQL Databases
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_service_db
    ports:
      - "3301:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - rental-network

  mysql-room:
    image: mysql:8.0
    container_name: mysql-room
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: room_service_db
    ports:
      - "3302:3306"
    volumes:
      - mysql-room-data:/var/lib/mysql
    networks:
      - rental-network

  mysql-booking:
    image: mysql:8.0
    container_name: mysql-booking
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booking_service_db
    ports:
      - "3303:3306"
    volumes:
      - mysql-booking-data:/var/lib/mysql
    networks:
      - rental-network

  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_service_db
    ports:
      - "3304:3306"
    volumes:
      - mysql-payment-data:/var/lib/mysql
    networks:
      - rental-network

  # Eureka Service Discovery
  eureka-server:
    image: steeltoeoss/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge

volumes:
  mysql-user-data:
  mysql-room-data:
  mysql-booking-data:
  mysql-payment-data: